CREATE  TABLE FESTIVAL(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(30),
LOCALIZACION VARCHAR2(30),
PROVINCIA VARCHAR2(30),
PARKING VARCHAR2(2),
GENERO VARCHAR2(30),
GRUPOS VARCHAR2(400),
FECHA VARCHAR2(30),
DURACION NUMBER,
PRECIO NUMBER(5,2));
/

INSERT INTO FESTIVAL VALUES(1,'VIÑAROCK','VILLAROBLEDO','MADRID', 'SI','ROCK','THE SKATALITES, THE RUMJACKS,EXTREMODURO,LA RAIZ, MANOLO KABEZABOLO,LA PEGATINA,VETUSTA MORLA','25/07/2019',5,60.49);
INSERT INTO FESTIVAL VALUES(2,'SOUND ISIDRO','MADRID','MADRID', 'SI','ELECTRÓNICA','DERBY MOTORETA,JAMES HOLDEN,LEE FIELDS AND THE EXPRESSIONS,AKAN,CUCHILLO DE FUEGO,CUPIDO,JAVIERA MENA','08/05/2019',4,50);
INSERT INTO FESTIVAL VALUES(3,'ALICANTE SPRING FESTIVAL','ELCHE','ALICANTE', 'SI','INDIE','LOVE OF LESBIAN,ROZALEN,FANGORIA,MISS CAFEINA,VIVA SUECIA,CAROLINA DURANTE,SECOND,CARLOS SADNESS','24/05/2019',2,37);
INSERT INTO FESTIVAL VALUES(4,'FÁCYL FESTIVAL','SALAMANCA','SALAMANCA', 'NO','FUSION','JUAN PERRO,LA EXCEPCION,LOS PUNSETES,OFUNKILLO,SOBER, AGORAPHOBIA,DELAPORTE,FEMI KUTI','29/05/2019',4,0);
INSERT INTO FESTIVAL VALUES(5,'OURENROCK SOUND','BENPOSTA','OURENSE','SI','ROCK','BOIKOT,TRIANGULO DE AMOR BIZARRO,CAROLINA DURANTE,LA PEGATINA,ZOO,DAKIDARRIA,SONS OF AGUIRRE,BEMBA SAOCO','30/05/2019',2,31.99);
INSERT INTO FESTIVAL VALUES(6,'PRIMAVERA SOUND','BARCELONA','BARCELONA','NO','ELECTRÓNICA','ERYKAH BADU,FUTURE,INTERPOL,J BALVIN,JANELLE MOANE,MILEY CIRUS,ROSALIA,SOLANGE','30/05/2019',3,195);
INSERT INTO FESTIVAL VALUES(7,'BULL MUSIC FESTIVAL','GRANADA','GRANADA','SI','FUSION','MAGO DE OZ,BERET,AYAX Y PROK,C TANGANA,FUEL FANDANGO,GREEN VALLEY,JUANITO MAKANDE,LA PEGATINA','31/05/2019',2,41.99);
INSERT INTO FESTIVAL VALUES(8,'CAPITAL FEST','TALAVERA DE LA REINA','TOLEDO','SI','INDIE','DORIAN,IVAN FERREIRO,LA MODA,MISS CAFEINA,SIDECARS,FULL,KUVE,TU OTRA BONITA','31/05/2019',2,40);
INSERT INTO FESTIVAL VALUES(9,'SOULVILLE FESTIVAL','SEVILLA','SEVILLA','NO','SOUL','ARETHA SOUL DIVAS,DRY MARTINA,LOS MAMBO JAMBO,SILVERBACKS','31/05/2019',1,19.99);
INSERT INTO FESTIVAL VALUES(10,'MIL FESTIVAL','TERUEL','TERUEL','SI','INDIE','ANDRES CALAMARO,DANI MASI,DAVID CIVERA,JAVIER OJEDA,MUCHO,WISE MEN PROJECT,ZAHARA','31/05/2019',3,49.49);
INSERT INTO FESTIVAL VALUES(11,'SEGO ROCK','CASTRO DE FUENTIDUEÑA','SEGOVIA','NO','ROCK','GATILLAZO,BOIKOT,REINCIDENTES,DEBRUCES,DESASTRE,EUKZ,KOAKZION,ORRI BERDEA','31/05/2019',2,24);
INSERT INTO FESTIVAL VALUES(12,'FESTIVAL IN-SOMNI','SALT','GIRONA','SI','INDIE','ELI PAPER BOY,MARKY RAMONE,JOANA SERRAT,GOULAMAS K,HELLOISA,EBRI KNIGHT,THE PICTUREBOOKS,WALTRAPA CASHMAKERS','07/06/2019',4,29.49);
INSERT INTO FESTIVAL VALUES(13,'PALENCIA SONORA','PALENCIA','PALENCIA','NO','INDIE','ROOSEVELT,IVAN FERREIRO,ZAHARA,VIVA SUECIA,LOS PILOTOS,MONARCHY,LA CASA AZUL,SHINOVA,LOS VINAGRES,TOMASITO','06/06/2019',3,50.29);
INSERT INTO FESTIVAL VALUES(14,'CULTURA INQUIETA','GETAFE','MADRID','SI','FUSION','JUANITO MAKANDE,DEPEDRO,PAJARO,MACACO,ISEO AND DODOSOUND,LUZ CASAL,RULO Y LA CONTRABANDA,MIKEL ERENTXUN,NACHA POP','29/06/2019',5,30);
INSERT INTO FESTIVAL VALUES(15,'NOCHES DEL BOTANICO','MADRID','MADRID','NO','FUSION','THE ROOTS,JUANES,DIEGO EL CIGALA,NIÑA PASTORI,LP,ORISHAS,KEANE,MELODY GARDOT,SNARKY PUPPY,GEORGE BENSON,THE WATERBOYS,ANA BELEN,BEIRUT','20/06/2019',25,45);
INSERT INTO FESTIVAL VALUES(16,'DOWNLOAD FESTIVAL','MADRID','MADRID','NO','ROCK','SCORPIONS,SABATON,PAPA ROACH,TURBONEGRO,SLIPKNOT,SUM 41,ARCHITECTS,SOULFLY,TOOL,TOUNDRA','28/06/2019',3,125.59);
INSERT INTO FESTIVAL VALUES(17,'PURPLE WEEKEND','LEÓN','LEÓN','SI','ROCK','GORILLA,KEN STRINGFELLOW,LOS MODERNOS,THE TRIP TAKERS,PAUL COLLINS,THE GENTLEMAN AGREEMENTS','06/12/2019',3,56.50);
commit;